### ISSUE TITLE
Render the King's response in html document (Rough Draft)

### ISSUE THREAD

**Issue by scybersec** [awr7/MoM#10]
We need to make it easier to read by rendering the response to html like in the video. Tired of the terminal and if it doesn't work. It's cool we will just go back to the terminal version.

**Comment by awr7** [comment]
This looks good! I think we can expand on this and make it a whole GUI to completely cut off the need of the terminal. This way we send our prompts straight on the browser and get our responses there as well.

**Comment by awr7** [comment]
If we do decide to go on the whole GUI route, we could probably use some lightweight python web framework like streamlit or flask. Or if we really want to be cool we have our bread and butter react or angular frontend that we know we would make beautifully and then connect this to a flask backend to handle API requests. basically flask would run our script and return the results to our frontend.

**Comment by awr7** [comment]
this is some example in streamlit:
https://llm-examples.streamlit.app/

this is an example in flask:
https://www.youtube.com/watch?v=70H_7C0kMbI

**Comment by scybersec** [comment]
I would opt for the streamlit because of the low overhead and given the scope of the project. However, If you feel like flask/angular/react route can be fruitful then i'm fully on board with that too.
